spring:
  application:
    name: preview_match_designer
  jpa:
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/match_design
    username: match_design
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas:
      - public


server:
  port: 8081
search:
  url:
    plumbing:
      santehnika-online: https://santehnika-online.ru
      vseinstrumenti: https://www.vseinstrumenti.ru


